### ISSUE TITLE
Comments about advanced despatch advice from TC440 WG7

### ISSUE THREAD

**Issue by PeterLBorresen** [OpenPEPPOL/logistics-bis#67]
•	Use same party template for all parties (unless there is a business reason for not have all the information)
•	Remove cac:DeliveryCustomerParty/ cac:DeliveryContact. Use cac:DeliveryCustomerParty/cac: Party/ cac:Contact in stead
•	Make shipment mandatory, but consignment optional.
•	Move gross weight, gross volume and total transport handling unit quantity to consignment since a shipment only can contain one consignment (optional)
•	Carrier party will be structured like the other parties, but also include a person.
•	The transportation service in the model is used for specifying the carbon foot print. This will not be acknowledged by the group. It is recommended to use an updated model from UBL 2.4. This will be presented at the next meeting.
•	The Transport means listed in the despatch advice is the last mile.
•	WG7 recommand to use the Delivery ABIE as proposed by the Peppol structure in stead of the Transport event previous proposed.
•	Mode Location Coordinate to location instead of address. Please coordinate with the ontology project.
•	Use Depatch location instead of Despatch address so they are aligned with the Delivery location.
•	Transport handling unit should be present in case of all goods delivery inclusive bulk.

**Comment by JorgenErlandsson** [comment]
• Use same party template for all parties (unless there is a business reason for not have all the information)
        - About the same comment is received from the project group evaluation. 
        - I have presented three optional solutions to that - Keep it as it is, Go back to how it is in T16, Evaluate all parties again 
           from beginning.
• Remove cac:DeliveryCustomerParty/ cac:DeliveryContact. Use cac:DeliveryCustomerParty/cac: Party/ cac:Contact in stead
        - This proposal exists two times already. Propose to keep DeliveryContact (to keep it in line with T16) and remove the 
           contact in Party.
• Make shipment mandatory, but consignment optional.
        - Also this comment is a duplicate. To keep the T121 aligned with T16 we should not do this change. If we do it we need 
           to add a RFC to change T16 too.
• Move gross weight, gross volume and total transport handling unit quantity to consignment since a shipment only can 
   contain one consignment (optional)
        - Again that would mean that we need to create a RFC to change the T16 DespatchAdvice, and to me this is not that 
           important.
• Carrier party will be structured like the other parties, but also include a person.
        - See above comments on all parties.
• The transportation service in the model is used for specifying the carbon foot print. This will not be acknowledged by the 
   group. It is recommended to use an updated model from UBL 2.4. This will be presented at the next meeting.
        - When it is possible to use UBL 2.4 this will be possible to change. Now it is not, and we need to keep it as it is.
• The Transport means listed in the despatch advice is the last mile.
        - Correct, should be used only when consignor knows it.
• WG7 recommand to use the Delivery ABIE as proposed by the Peppol structure in stead of the Transport event previous 
   proposed.
        - I do not understand this comment/request. Need clarification .
• Mode Location Coordinate to location instead of address. Please coordinate with the ontology project.
       - ?
• Use Depatch location instead of Despatch address so they are aligned with the Delivery location.
      - This is also a duplicate issue. DespatchLocation would be better, but the T16 use the DespatchAddress.
• Transport handling unit should be present in case of all goods delivery inclusive bulk.
      - There are many situations where the consignor cannot describe any THUs. We can not make it mandatory.

**Comment by agrindst** [comment]
Closing this issue, because these comments are duplicates with the comments from the Work group.
